SOURCES	     += ../pysoundanalyser/__main__.py
SOURCES	     += ../pysoundanalyser/dialog_apply_filter.py
SOURCES	     += ../pysoundanalyser/dialog_change_channel.py
SOURCES	     += ../pysoundanalyser/dialog_concatenate.py
SOURCES	     += ../pysoundanalyser/dialog_edit_preferences.py
SOURCES	     += ../pysoundanalyser/dialog_generate_noise.py
SOURCES	     += ../pysoundanalyser/dialog_generate_sound.py
SOURCES	     += ../pysoundanalyser/dialog_generate_sinusoid.py
SOURCES	     += ../pysoundanalyser/dialog_resample.py
SOURCES	     += ../pysoundanalyser/dialog_save_sound.py
SOURCES	     += ../pysoundanalyser/random_id.py
SOURCES	     += ../pysoundanalyser/utility_functions.py
SOURCES	     += ../pysoundanalyser/win_acf_plot.py
SOURCES	     += ../pysoundanalyser/win_autocorrelogram_plot.py
SOURCES	     += ../pysoundanalyser/win_spectrogram_plot.py
SOURCES	     += ../pysoundanalyser/win_spectrum_plot.py
SOURCES	     += ../pysoundanalyser/win_waveform_plot.py
SOURCES	     += ../pysoundanalyser/sndlib.py
TRANSLATIONS += pysoundanalyser_it.ts pysoundanalyser_fr.ts pysoundanalyser_en_GB.ts pysoundanalyser_el.ts pysoundanalyser_es.ts pysoundanalyser_de.ts pysoundanalyser_ru.ts

