SOURCES	     += ../pysoundanalyser.pyw
SOURCES	     += ../pysoundanalyser_pack/dialog_apply_filter.py
SOURCES	     += ../pysoundanalyser_pack/dialog_change_channel.py
SOURCES	     += ../pysoundanalyser_pack/dialog_concatenate.py
SOURCES	     += ../pysoundanalyser_pack/dialog_edit_preferences.py
SOURCES	     += ../pysoundanalyser_pack/dialog_generate_noise.py
SOURCES	     += ../pysoundanalyser_pack/dialog_generate_sound.py
SOURCES	     += ../pysoundanalyser_pack/dialog_generate_sinusoid.py
SOURCES	     += ../pysoundanalyser_pack/dialog_resample.py
SOURCES	     += ../pysoundanalyser_pack/dialog_save_sound.py
SOURCES	     += ../pysoundanalyser_pack/random_id.py
SOURCES	     += ../pysoundanalyser_pack/utility_functions.py
SOURCES	     += ../pysoundanalyser_pack/win_acf_plot.py
SOURCES	     += ../pysoundanalyser_pack/win_autocorrelogram_plot.py
SOURCES	     += ../pysoundanalyser_pack/win_spectrogram_plot.py
SOURCES	     += ../pysoundanalyser_pack/win_spectrum_plot.py
SOURCES	     += ../pysoundanalyser_pack/win_waveform_plot.py
TRANSLATIONS += pysoundanalyser_it.ts pysoundanalyser_fr.ts pysoundanalyser_en_GB.ts pysoundanalyser_el.ts pysoundanalyser_es.ts pysoundanalyser_de.ts pysoundanalyser_ru.ts

